const DB_NAME="scada_ptar_bellavista_local", STORE="registros", DEVICE_KEY="scada_device_id", API_SYNC="/api/sync";
const $=id=>document.getElementById(id); let db; let currentType="ph_entrada";
const MODULES=[
 ['Dashboard','dashboard'],['pH de entrada','ph_entrada'],['pH de salida','ph_salida'],['Estadísticas','estadisticas'],['Aforo volumétrico','aforo'],['Dosificación','dosificacion'],['Lavado de unidades','lavado'],['Horómetro bomba','horometro'],['Mantenimiento','mantenimiento'],['Horarios de turno','horarios'],['Operador','operador'],['Novedades','novedad'],['Evidencias','evidencias'],['Planillas mensuales','planillas'],['Sincronización','sincronizacion']
];
const SCHEMAS={
 ph_entrada:[['ph','pH medido','number','0.01']],ph_salida:[['ph','pH medido','number','0.01']],
 aforo:[['volumen_l','Volumen (L)','number','0.01'],['tiempo_s','Tiempo (s)','number','0.01']],
 dosificacion:[['tanque','Tanque/unidad','text'],['producto','Producto químico','text'],['consumo_l','Consumo (L)','number','0.01']],
 lavado:[['unidad','Unidad lavada','text'],['estado','Estado','select',['Completado','Parcial','Pendiente']],['tiempo','Tiempo empleado','text']],
 horometro:[['equipo','Equipo','text'],['lectura_h','Lectura del horómetro (h)','number','0.1']],
 mantenimiento:[['equipo','Equipo','text'],['tipo_mantenimiento','Tipo de mantenimiento','select',['Preventivo','Correctivo','Predictivo']],['prioridad','Prioridad','select',['Baja','Media','Alta']],['descripcion','Descripción','text'],['estado','Estado','select',['Pendiente','En proceso','Realizado']]],
 novedad:[['categoria','Categoría de novedad','text'],['prioridad','Prioridad','select',['Baja','Media','Alta']],['estado','Estado','select',['Pendiente','En proceso','Resuelta']]],
 horarios:[['turno','Turno','select',['Mañana','Tarde','Noche']],['hora_inicio','Hora de inicio','text'],['hora_fin','Hora de finalización','text']],
 operador:[['nombre_operador','Nombre del operador','text'],['turno','Turno','select',['Mañana','Tarde','Noche']]],
 evidencias:[['archivo_nombre','Nombre de evidencia (referencia)','text'],['descripcion','Descripción','text']],
 dashboard:[['resumen','Resumen operativo','text']],estadisticas:[['indicador','Indicador','text'],['valor','Valor','text']],planillas:[['mes','Mes de la planilla','text'],['ano','Año','number','1']],sincronizacion:[['nota','Nota de sincronización','text']]
};
function uuid(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function deviceId(){let id=localStorage.getItem(DEVICE_KEY);if(!id){id=uuid();localStorage.setItem(DEVICE_KEY,id)}return id}
function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>req.result.createObjectStore(STORE,{keyPath:'id'});req.onsuccess=()=>{db=req.result;resolve(db)};req.onerror=()=>reject(req.error)})}
function allRecords(){return new Promise((resolve,reject)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function putRecord(x){return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(x);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
function deleteRecord(id){return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderMenu(){ $('moduleMenu').innerHTML=MODULES.map(([label,type])=>`<button type="button" class="module-btn ${type===currentType?'active':''}" data-type="${type}">${label}</button>`).join(''); document.querySelectorAll('.module-btn').forEach(b=>b.addEventListener('click',()=>selectModule(b.dataset.type))); }
function selectModule(type){currentType=type;$('tipo').value=type;$('formTitle').textContent=MODULES.find(m=>m[1]===type)?.[0]||'Nuevo registro';renderMenu();setFields();if(['dashboard','estadisticas','planillas','sincronizacion'].includes(type))$('observaciones').placeholder='Anota la consulta o actividad realizada; los informes completos se gestionan en el PC.'}
function setFields(){const fields=SCHEMAS[currentType]||[['descripcion','Descripción','text']];$('dynamicFields').innerHTML='<div class="field-grid">'+fields.map(([id,label,type,extra])=>{let input;if(type==='select')input=`<select id="f_${id}" required>${extra.map(x=>`<option>${x}</option>`).join('')}</select>`;else input=`<input id="f_${id}" type="${type}" ${extra?`step="${extra}"`:''} required>`;return `<label>${label}${input}</label>`}).join('')+'</div>'}
function collectData(){const d={};(SCHEMAS[currentType]||[['descripcion']]).forEach(([id])=>{const el=$('f_'+id);if(el)d[id]=el.type==='number'?Number(el.value):el.value.trim()});d.observaciones=$('observaciones').value.trim();return d}
async function renderCounts(){const rows=await allRecords();$('counts').textContent=`${rows.length} registro(s) pendiente(s) en este dispositivo`;}
async function checkConnection(){if(!navigator.onLine){$('connection').textContent='Sin señal · modo offline';return false}try{const r=await fetch('/api/health',{cache:'no-store'});if(!r.ok)throw 0;$('connection').textContent='Conectado a la nube';return true}catch{$('connection').textContent='Servidor no disponible · modo offline';return false}}
async function syncPending(){if(!(await checkConnection())){$('syncMessage').textContent='Sin conexión. Los registros nuevos se conservan temporalmente en el teléfono.';return}const rows=await allRecords();if(!rows.length){$('syncMessage').textContent='No hay registros pendientes.';return}$('syncMessage').textContent='Enviando registros a la nube…';try{const res=await fetch(API_SYNC,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({device_id:deviceId(),registros:rows.map(r=>({sync_uuid:r.id,tabla:r.tipo,fecha:r.fecha_hora,operador:r.operador,datos:r.datos,device_id:r.dispositivo_id}))})});if(!res.ok)throw Error('Error de servidor');const data=await res.json();const ok=new Set(data.confirmados||[]);for(const r of rows)if(ok.has(r.id))await deleteRecord(r.id);await renderCounts();$('syncMessage').textContent=`Nube actualizada: ${ok.size} registro(s) guardado(s). Copia local temporal eliminada para liberar espacio.`}catch(e){$('syncMessage').textContent='No se completó la sincronización. Los datos siguen temporalmente en el teléfono; inténtalo de nuevo.'}}
$('recordForm').addEventListener('submit',async e=>{e.preventDefault();const record={id:uuid(),tipo:currentType,fecha_hora:$('fechaHora').value,operador:$('operador').value.trim(),datos:collectData(),dispositivo_id:deviceId(),creado_local:new Date().toISOString()};if(!record.operador){alert('Escribe el nombre del operador');return}await putRecord(record);$('recordForm').reset();$('fechaHora').value=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);setFields();await renderCounts();$('syncMessage').textContent='Guardado temporalmente. Se enviará a la nube cuando haya conexión.';if(navigator.onLine)syncPending()});
$('syncBtn').addEventListener('click',syncPending);window.addEventListener('online',syncPending);window.addEventListener('online',checkConnection);
(async()=>{try{await openDB();renderMenu();selectModule('ph_entrada');$('fechaHora').value=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);await renderCounts();await checkConnection();if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{})}catch(e){$('syncMessage').textContent='No se pudo iniciar almacenamiento temporal del navegador.'}})();
